# Generated by Django 3.1.7 on 2023-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gosc_hotelowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Gosc_hotelowy',
                'db_table': 'Gosc_hotelowy',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hotel',
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_pokoju', models.IntegerField()),
                ('typ_pokoju', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pokoj',
                'db_table': 'Pokoj',
            },
        ),
        migrations.CreateModel(
            name='Recepcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepcja', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Recepcja',
                'db_table': 'Recepcja',
            },
        ),
        migrations.CreateModel(
            name='Typ_pokoju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_typu_pokoju', models.CharField(max_length=150)),
                ('ilosc_osob', models.IntegerField()),
                ('cena', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Typ_pokoju',
                'db_table': 'Typ_pokoju',
            },
        ),
    ]
