# Generated by Django 3.1.7 on 2023-11-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gosc_hotelowy',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Pokoj',
        ),
        migrations.DeleteModel(
            name='Recepcja',
        ),
        migrations.DeleteModel(
            name='Typ_pokoju',
        ),
    ]
